//Anandi and Jagya were getting married again when they have achieved proper age. 
//Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. 
//Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. 
//Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
//The generated blessing is a common subsequence of length K of the two blessings he has. 
//Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum.
//If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). 
//Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
//Input Specification
//First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
//Output Specification
//Output consists of t lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.
//Constraint
//1 <= t <= 50
//
//1 <= length(b1) , length(b2) <= 100 
//
//1 <= K <= 100



#include <bits/stdc++.h>
#include<algorithm>
#include<string>
using namespace std;

long solve(string s1,string s2,int l1,int l2,int count,int***output)
{
    if(count==0)
    {
        return 0;
    }
    
    if((l1==0||l2==0))
    {
        return INT_MIN;
    }
    
    if(output[l1][l2][count]!=-1)
        return output[l1][l2][count];
    
    long res;
    if(s1.substr(0,1)==s2.substr(0,1))
        { int a=s1[0];
          long res1=a+solve(s1.substr(1,l1-1),s2.substr(1,l2-1),l1-1,l2-1,count-1,output);
          long res2=max(solve(s1,s2.substr(1,l2-1),l1,l2-1,count,output),solve(s1.substr(1,l1-1),s2,l1-1,l2,count,output));
          res=max(res1,res2);
          
        
        }
    else
        {long res1=solve(s1,s2.substr(1,l2-1),l1,l2-1,count,output);
         long res2=solve(s1.substr(1,l1-1),s2,l1-1,l2,count,output);
         res=max(res1,res2);
        
        }
    output[l1][l2][count]=res;
    return res;
}

int main()
{   int t;
    cin>>t;
    while(t--)
        {string s1,s2;
         cin>>s1>>s2;
         int l1=s1.length();
         int l2=s2.length();
         int k;
         
         cin>>k;
         
         int***output=new int**[l1+1];
         for(int i=0;i<l1+1;i++)
             {output[i]=new int*[l2+1];
              for(int j=0;j<l2+1;j++)
                  {output[i][j]=new int[k+1];
                   for(int m=0;m<k+1;m++)
                       { output[i][j][m]=-1;
                       }
                  
                  }
             
             }
         long result=solve(s1,s2,l1,l2,k,output);
         if(result<0)
             result=0;
             
         
         cout<<result<<endl;
        
        }
    return 0;
}

